### PR TITLE
Fix pre commit (add --files)

### PR DESCRIPTION
**Pull request by mdeweerd**
# Fix pre commit (add --files)

### CODE REVIEW

**Comment by frederic34** [comment]
@mdeweerd are you testing on my fork ?

**Comment by mdeweerd** [comment]
I was amending your PR ;-).

**Comment by frederic34** [comment]
which PR ?

**Comment by frederic34** [comment]
you have to open your PR on frederic34:branch-of-pr ?

**Comment by mdeweerd** [comment]
I checked the result of the PR, so:
- This allows to fix the issue I noticed in ci;
- Allows to test the fix;
- Would make only one PR in the end.

So if you add this PR, I'll remove the other one I opened on develop on Dolibarr.
However, I did not choose the correct target here - I'll fix that.

**Pull request merged**
